# Generated by Django 4.2.27 on 2026-01-28 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='地区代码')),
                ('name', models.CharField(max_length=50, verbose_name='地区名称')),
                ('domain', models.CharField(max_length=100, verbose_name='域名')),
                ('path', models.CharField(default='scdc.htm', max_length=100, verbose_name='路径')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '地区',
                'verbose_name_plural': '地区管理',
                'db_table': 'region',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('color', models.CharField(default='#00D2FF', max_length=20, verbose_name='颜色')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '标签分类',
                'verbose_name_plural': '标签分类管理',
                'db_table': 'tag_category',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名称')),
                ('keywords', models.TextField(blank=True, help_text='用于自动匹配的关键词', verbose_name='关键词（逗号分隔）')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('color', models.CharField(default='#00D2FF', max_length=20, verbose_name='颜色')),
                ('is_auto', models.BooleanField(default=True, verbose_name='自动匹配')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.tagcategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签管理',
                'db_table': 'tag',
                'ordering': ['category', 'sort'],
            },
        ),
        migrations.CreateModel(
            name='CrawlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(blank=True, max_length=50, verbose_name='地区名称')),
                ('total_crawled', models.IntegerField(default=0, verbose_name='爬取总数')),
                ('new_count', models.IntegerField(default=0, verbose_name='新增数量')),
                ('status', models.CharField(choices=[('success', '成功'), ('error', '失败'), ('empty', '无新数据')], max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('crawl_time', models.DateTimeField(auto_now_add=True, verbose_name='爬取时间')),
                ('duration', models.FloatField(default=0, verbose_name='耗时（秒）')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.region', verbose_name='地区')),
            ],
            options={
                'verbose_name': '爬取日志',
                'verbose_name_plural': '爬取日志管理',
                'db_table': 'crawl_log',
                'ordering': ['-crawl_time'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='原文链接')),
                ('source', models.CharField(default='清风网', max_length=100, verbose_name='来源')),
                ('region_name', models.CharField(blank=True, max_length=50, verbose_name='地区名称')),
                ('menu', models.CharField(blank=True, max_length=100, verbose_name='菜单分类')),
                ('submenu', models.CharField(blank=True, max_length=100, verbose_name='子菜单')),
                ('tag_names', models.CharField(blank=True, max_length=500, verbose_name='标签名称')),
                ('crawl_time', models.DateTimeField(auto_now_add=True, verbose_name='爬取时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='published', max_length=20, verbose_name='状态')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.region', verbose_name='地区')),
                ('tags', models.ManyToManyField(blank=True, to='news.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻管理',
                'db_table': 'news',
                'ordering': ['-date', '-crawl_time'],
                'indexes': [models.Index(fields=['date'], name='news_date_0a9db5_idx'), models.Index(fields=['region'], name='news_region__3000f1_idx'), models.Index(fields=['url'], name='news_url_306ab1_idx')],
            },
        ),
    ]
