# Generated by Django 4.2.27 on 2026-01-28 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('all', '全量爬取'), ('single', '单地区爬取'), ('manual', '手动触发')], default='manual', max_length=20, verbose_name='任务类型')),
                ('region_code', models.CharField(blank=True, max_length=20, verbose_name='地区代码')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('success', '成功'), ('failed', '失败'), ('stopped', '已停止')], default='pending', max_length=20, verbose_name='状态')),
                ('total_crawled', models.IntegerField(default=0, verbose_name='爬取总数')),
                ('new_count', models.IntegerField(default=0, verbose_name='新增数量')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.region', verbose_name='地区')),
            ],
            options={
                'verbose_name': '爬虫任务',
                'verbose_name_plural': '爬虫任务管理',
                'db_table': 'crawl_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '新增'), ('update', '修改'), ('delete', '删除'), ('crawl', '爬取'), ('export', '导出'), ('login', '登录')], max_length=20, verbose_name='操作类型')),
                ('content_type', models.CharField(max_length=50, verbose_name='内容类型')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='对象ID')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='对象描述')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='用户IP')),
                ('detail', models.TextField(blank=True, verbose_name='详细信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志管理',
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
