# Generated by Django 4.2.27 on 2026-01-29 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_crawltask_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='corrected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='修正时间'),
        ),
        migrations.AddField(
            model_name='news',
            name='corrected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_news', to=settings.AUTH_USER_MODEL, verbose_name='修正人'),
        ),
        migrations.AddField(
            model_name='news',
            name='correction_reason',
            field=models.TextField(blank=True, verbose_name='修正原因'),
        ),
        migrations.AddField(
            model_name='news',
            name='is_manual_corrected',
            field=models.BooleanField(default=False, verbose_name='已手动修正'),
        ),
        migrations.AddField(
            model_name='news',
            name='manual_tag_names',
            field=models.CharField(blank=True, max_length=500, verbose_name='手动标签名称'),
        ),
        migrations.AddField(
            model_name='news',
            name='manual_tags',
            field=models.ManyToManyField(blank=True, related_name='manual_news', to='news.tag', verbose_name='手动修正标签'),
        ),
        migrations.CreateModel(
            name='SupervisionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='事项名称')),
                ('year', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], default='2026', max_length=4, verbose_name='年份')),
                ('month', models.CharField(choices=[('1', '1月'), ('2', '2月'), ('3', '3月'), ('4', '4月'), ('5', '5月'), ('6', '6月'), ('7', '7月'), ('8', '8月'), ('9', '9月'), ('10', '10月'), ('11', '11月'), ('12', '12月')], default='1', max_length=2, verbose_name='月份')),
                ('core_keywords', models.TextField(blank=True, help_text='核心关键词，用逗号分隔', verbose_name='核心关键词')),
                ('synonyms', models.TextField(blank=True, help_text='近义词，用逗号分隔', verbose_name='近义词')),
                ('context_words', models.TextField(blank=True, help_text='上下文行动词，用逗号分隔', verbose_name='上下文行动词')),
                ('description', models.TextField(blank=True, verbose_name='事项描述')),
                ('standard', models.TextField(blank=True, verbose_name='判定标准')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.tagcategory', verbose_name='监督分类')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '监督事项清单',
                'verbose_name_plural': '监督事项清单管理',
                'db_table': 'supervision_item',
                'ordering': ['year', 'month', 'sort'],
                'unique_together': {('name', 'year', 'month')},
            },
        ),
    ]
