# Generated by Django 4.2.27 on 2026-01-29 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('trigger_type', models.CharField(choices=[('interval', '间隔执行'), ('cron', '定时执行')], default='interval', max_length=20, verbose_name='触发类型')),
                ('interval_hours', models.IntegerField(default=4, help_text='间隔执行时有效', verbose_name='间隔小时数')),
                ('cron_hour', models.IntegerField(default=8, help_text='定时执行时有效（0-23）', verbose_name='小时')),
                ('cron_minute', models.IntegerField(default=0, help_text='定时执行时有效（0-59）', verbose_name='分钟')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('max_instances', models.IntegerField(default=1, help_text='同时运行的最大任务数', verbose_name='最大并发数')),
                ('crawl_all_regions', models.BooleanField(default=True, verbose_name='爬取所有地区')),
                ('region_codes', models.TextField(blank=True, help_text='爬取所有地区时忽略此选项，多个地区用逗号分隔，如：xian,baoji', verbose_name='指定地区')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '爬虫任务配置',
                'verbose_name_plural': '爬虫任务配置管理',
                'db_table': 'crawl_config',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlScheduleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_time', models.DateTimeField(auto_now_add=True, verbose_name='触发时间')),
                ('status', models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('failed', '失败')], default='running', max_length=20, verbose_name='状态')),
                ('total_crawled', models.IntegerField(default=0, verbose_name='爬取总数')),
                ('new_count', models.IntegerField(default=0, verbose_name='新增数量')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('duration', models.FloatField(default=0, verbose_name='耗时（秒）')),
                ('config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crawler.crawlconfig', verbose_name='任务配置')),
            ],
            options={
                'verbose_name': '调度执行日志',
                'verbose_name_plural': '调度执行日志管理',
                'db_table': 'crawl_schedule_log',
                'ordering': ['-trigger_time'],
            },
        ),
    ]
